package ca.mcmaster.se2aa4.mazerunner;
import static org.junit.jupiter.api.Assertions.*;
import java.util.Map;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

public class GraphSolverTest {
    private GraphSolver graphSolver;
    private Maze maze;

    @BeforeEach
    void setUp() throws Exception {
        
        graphSolver = new GraphSolver();
    }

    //test if the path for giant mazegenerated by bfs is actually valid
    @Test
    void SolveWithBFSTestGiant() throws Exception {
        maze = new Maze("./examples/giant.maz.txt"); 
        Path sol = graphSolver.solve(maze);
        assertTrue(maze.validatePath(sol));
    }

    @Test
    void SolveWithBFSTestDirect() throws Exception {
        maze = new Maze("./examples/direct.maz.txt"); 
        Path sol = graphSolver.solve(maze);
        assertTrue(maze.validatePath(sol));
    }

    

   
}